# Generated by Django 4.0.3 on 2022-04-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=30)),
                ('caticon', models.ImageField(upload_to='')),
                ('catdesc', models.CharField(max_length=2000)),
                ('regdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scatname', models.CharField(max_length=30)),
                ('scicon', models.ImageField(upload_to='')),
                ('scdesc', models.CharField(max_length=2000)),
                ('regdate', models.DateField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
            ],
        ),
    ]
