# Generated by Django 4.0.3 on 2022-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_category_regdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('adpass', models.CharField(max_length=15)),
            ],
        ),
    ]
