# Generated by Django 4.0.3 on 2022-05-15 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_regadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='regadmin',
            name='regdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
