# Generated by Django 4.0.3 on 2022-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_regadmin_regdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regadmin',
            name='id',
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
