# Generated by Django 4.0.3 on 2022-05-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_category_caticon_alter_subcategory_scicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='caticon',
            field=models.ImageField(default='', upload_to='adminapp/images/'),
        ),
    ]
