# Generated by Django 4.0.3 on 2022-04-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('mobno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('udesc', models.CharField(max_length=1000)),
            ],
        ),
    ]
