# Generated by Django 4.0.3 on 2022-04-17 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 4, 17, 15, 3, 9, 356600, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
