# Generated by Django 4.0.3 on 2022-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_contacts_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unm', models.CharField(max_length=30)),
                ('mno', models.IntegerField()),
                ('eid', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=30)),
                ('status', models.CharField(default='No', max_length=10)),
                ('regdate', models.DateField()),
            ],
        ),
    ]
