# Generated by Django 4.0.3 on 2022-05-08 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_category_regdate'),
        ('userapp', '0003_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addblog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=250)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.register')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.subcategory')),
            ],
        ),
    ]
