# Generated by Django 4.0.3 on 2022-05-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_addblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addblog',
            old_name='eid',
            new_name='unm',
        ),
        migrations.RemoveField(
            model_name='addblog',
            name='author',
        ),
    ]
