# Generated by Django 4.0.3 on 2022-05-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_eid_addblog_unm_remove_addblog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addblog',
            name='unm',
        ),
    ]
