# Generated by Django 4.0.3 on 2022-05-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_addblog_unm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='unm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userapp.register'),
        ),
    ]
