# Generated by Django 4.0.3 on 2022-05-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_addblog_unm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addblog',
        ),
    ]
