# Generated by Django 4.0.3 on 2022-05-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_blog_bl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bl_image',
            field=models.ImageField(default='', upload_to='userapp/blog/images'),
        ),
    ]
